INKTest.skills = () => [
  { Name: 'athletics', NPCName: 'npc_athletics' },
  { Name: 'acrobatics', NPCName: 'npc_acrobatics' },
  { Name: 'sleight_of_hand', NPCName: 'npc_sleight_of_hand' },
  { Name: 'stealth', NPCName: 'npc_stealth' },
  { Name: 'arcana', NPCName: 'npc_arcana' },
  { Name: 'history', NPCName: 'npc_history' },
  { Name: 'investigation', NPCName: 'npc_investigation' },
  { Name: 'nature', NPCName: 'npc_nature' },
  { Name: 'animal_handling', NPCName: 'npc_animal_handling' },
  { Name: 'insight', NPCName: 'npc_insight' },
  { Name: 'medicine', NPCName: 'npc_medicine' },
  { Name: 'perception', NPCName: 'npc_perception' },
  { Name: 'survival', NPCName: 'npc_survival' },
  { Name: 'intimidation', NPCName: 'npc_intimidation' },
  { Name: 'performance', NPCName: 'npc_performance' },
  { Name: 'persuasion', NPCName: 'npc_persuasion' },
];
